
services:
  flask-app:
    container_name: "flask-app-container"
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      -  CapstoneNetwork

  db:
    container_name: "mysql-container"
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      -  CapstoneNetwork
    restart: always
  redis:
    container_name: "redis-container"
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      -  CapstoneNetwork
    
networks:
  CapstoneNetwork:
    driver: bridge
