name: ci

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #        - main
      
jobs:
  pu:
    runs-on: ubuntu-latest
    steps:
      -
        name: fetch code from repository
        uses: actions/checkout@v4
      

        
        # name: Super-linter
        # uses: super-linter/super-linter@v7.1.0 
        # env:
      
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      -
        
  
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKER_TOKEN_PASSWORD }}
      -
        name: BuilD and push
        uses: docker/build-push-action@v6
        with:
          push: true

          tags: |
              mohammedmustaf/python:latest
              mohammedmustaf/python:${{ github.sha }}

              
