name: push-to-DockerHub

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #        - main
      
jobs:
  test-the-code:
    runs-on: ubuntu-latest
    steps:
    -
      name: fetch code from repository
      uses: actions/checkout@v4
    
    -
      name: rub the test command 
      run: python test_app.py

  push-to-DockerHub:
    runs-on: ubuntu-latest
    steps:
      -
        name: fetch code from repository
        uses: actions/checkout@v4
      
      -
        name: Login to Docker Hub mohammedmustaf repository
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKER_TOKEN_PASSWORD }}
      -
        name: BuilD and push
        uses: docker/build-push-action@v6
        with:
          push: true

          tags: 
              mohammedmustaf/python:latest
     

              
