name: push_WorkFlow

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: fetch code from repository
        uses: actions/checkout@v4
      -
  
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: BuilD and push
        uses: docker/build-push-action@v6
        with:
          push: true

          tags: |
              mohammedalharbi/python:latest
              mohammedalharbi/python:${{ github.sha }}

              
